nameOverride: svc-auth

replicaCount: 2

imagePullSecrets:
  - regcred

image:
  env:
    - name: NODE_ENV
      value: production
    - name: SERVICE_NAME
      value: svc-auth
  envFrom:
    - configMapRef:
        name: svc-auth-prd-config
    - secretRef:
        name: svc-auth-prd-secrets
        optional: true

service:
  ports:
    - name: http
      port: 80
      targetPort: http
      containerPort: 4010

ingress:
  enabled: true
  className: kong
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-http
    konghq.com/strip-path: "true"
  hosts:
    - host: api.mereb.app
      paths:
        - path: /auth
          pathType: Prefix
          servicePort: http
  tls:
    - secretName: auth-prd-tls
      hosts:
        - api.mereb.app

configMap:
  enabled: true
  nameOverride: svc-auth-prd-config
  data:
    PORT: "4010"
    OIDC_ISSUER: https://auth.mereb.app/realms/mereb
    OIDC_AUDIENCE: mereb

resources:
  requests:
    cpu: 100m
    memory: 160Mi
  limits:
    cpu: 300m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
