replicaCount: 1

configMap:
  data:
    PORT: "4010"
    SPLUNK_HEC_URL: http://splunk-prd.platform-prd.svc.cluster.local:8088/services/collector/event
    SPLUNK_HEC_INDEX: logs-stg

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
