replicaCount: 2

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

configMap:
  data:
    PORT: "4010"
    SPLUNK_HEC_URL: http://splunk-prd.platform-prd.svc.cluster.local:8088/services/collector/event
    SPLUNK_HEC_INDEX: logs-prd

resources:
  requests:
    cpu: 50m
    memory: 160Mi
  limits:
    cpu: 300m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
